FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y maven wget

RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt-get install -y ./google-chrome-stable_current_amd64.deb \
    && rm google-chrome-stable_current_amd64.deb

USER jenkins
