serenity.project.name=Laborator 6 VVSS
webdriver.driver=chrome
webdriver.autodownload=true
headless.mode=false

chrome.switches=--headless;--no-sandbox;--disable-dev-shm-usage;--disable-gpu;--window-size=1920,1080;--remote-allow-origins=*;--incognito;--disable-blink-features=AutomationControlled;--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

webdriver.timeouts.implicitlywait=10000
webdriver.timeouts.fluentwait=15000
